import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getLocale, setRequestLocale } from "next-intl/server";
import { fetchRankMathSeo, buildPageMetadata } from "@/lib/seo/server";
import { env } from "@/lib/env";
import { serverApi } from "@/lib/api/server";
import { normalizePage } from "@/lib/services/pages";
import { BlockRenderer } from "@/components/blocks/block-renderer";
import { GravityFormLoader } from "@/components/forms/gravity-form-loader";
import { ParsedHtml } from "@/components/ui/parsed-html";

export const revalidate = 300;

interface PageProps {
  params: Promise<{ slug: string }>;
}

/**
 * Pre-render only block-composed (Landing) pages here. Plain WP pages with their
 * own explicit routes (about, pricing, privacy-policy, …) are NOT generated by
 * this catch-all; any remaining plain pages resolve on-demand (ISR).
 */
export async function generateStaticParams() {
  try {
    const { items } = await serverApi.pages.list("landing-blocks");
    return (items ?? []).flatMap((p) => (p.slug ? [{ slug: p.slug }] : []));
  } catch {
    return [];
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  setRequestLocale(await getLocale());
  try {
    const [raw, seo] = await Promise.all([
      serverApi.pages.detail(slug),
      fetchRankMathSeo(`/${slug}`),
    ]);
    const page = normalizePage(raw);
    return buildPageMetadata(seo, {
      title: `${page.title} | Training Excellence`,
      description: page.excerpt || page.title,
      canonical: `${env.SITE_URL.replace(/\/$/, "")}/${slug}`,
    });
  } catch {
    return { title: "Page not found" };
  }
}

export default async function DynamicPage({ params }: PageProps) {
  const { slug } = await params;

  const raw = await serverApi.pages.detail(slug).catch(() => null);
  if (!raw) notFound();

  const page = normalizePage(raw);

  if (page.isBlocks) {
    return <BlockRenderer blocks={page.blocks} />;
  }

  // Plain WP page → render rendered content, then any [gravityform] embeds.
  return (
    <article className="py-12">
      <div className="container max-w-3xl">
        <h1 className="mb-6 font-suse text-3xl font-bold text-neutral-900 md:text-4xl">
          {page.title}
        </h1>
        <ParsedHtml
          as="div"
          className="prose-wp font-open-sans text-[#3b5374]"
          content={page.content}
        />

        {page.formIds.map((formId) => (
          <div key={formId} className="mt-10">
            <GravityFormLoader formId={formId} />
          </div>
        ))}
      </div>
    </article>
  );
}
