import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getLocale, setRequestLocale } from "next-intl/server";
import { fetchRankMathSeo, buildPageMetadata } from "@/lib/seo/server";
import { wpPath } from "@/lib/seo/wp-paths";
import { isServableWpPage } from "@/lib/seo/wp-pages";
import { env } from "@/lib/env";
import { serverApi } from "@/lib/api/server";
import { normalizePage } from "@/lib/services/pages";
import { isStaticParamsPlaceholder, withStaticParamsPlaceholder } from "@/lib/utils/static-params";
import { BlockRenderer } from "@/components/blocks/block-renderer";
import { GravityFormLoader } from "@/components/forms/gravity-form-loader";
import { ParsedHtml } from "@/components/ui/parsed-html";

export const revalidate = 300;
export const dynamicParams = true;

interface PageProps {
  params: Promise<{ slug: string }>;
}

/**
 * Pre-render only block-composed (Landing) pages here. Plain WP pages with their
 * own explicit routes (about, pricing, privacy-policy, …) are NOT generated by
 * this catch-all; any remaining plain pages resolve on-demand (ISR).
 *
 * An empty result is padded with a sentinel slug — see
 * `withStaticParamsPlaceholder` for why. Both `generateMetadata` and the page
 * short-circuit on it, so the build never fetches it.
 */
export async function generateStaticParams() {
  try {
    const { items } = await serverApi.pages.list("landing-blocks");
    return withStaticParamsPlaceholder(
      (items ?? []).flatMap((p) => (p.slug ? [{ slug: p.slug }] : [])),
    );
  } catch {
    return withStaticParamsPlaceholder([]);
  }
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  if (isStaticParamsPlaceholder(slug)) return { title: "Page not found" };
  setRequestLocale(await getLocale());
  try {
    const [raw, seo] = await Promise.all([
      serverApi.pages.detail(slug),
      fetchRankMathSeo(wpPath.page(slug)),
    ]);
    const page = normalizePage(raw);
    return buildPageMetadata(seo, {
      title: page.title,
      description: page.excerpt || page.title,
      canonical: `${env.SITE_URL.replace(/\/$/, "")}/${slug}`,
    });
  } catch {
    console.error(`Failed to generate metadata for page: ${slug}`);
    return { title: "Page not found" };
  }
}

export default async function DynamicPage({ params }: PageProps) {
  const { slug } = await params;
  if (isStaticParamsPlaceholder(slug)) notFound();
  let raw;
  try {
    raw = await serverApi.pages.detail(slug);
  } catch (error) {
    console.error(`Failed to fetch page: ${slug}`, error);
    notFound();
  }
  if (!raw) notFound();
  const page = normalizePage(raw);

  // WordPress answers 200 for pages this app has nothing to render — `/shop`
  // came back with no content, no blocks and a Rank Math 404 head, and was
  // served as an indexable "Page Not Found" at HTTP 200. A soft 404 spends
  // crawl budget and can be indexed as a real page.
  const seo = await fetchRankMathSeo(wpPath.page(slug));
  if (!isServableWpPage(page, seo?.canonical)) notFound();

  if (page.isBlocks) {
    return <BlockRenderer blocks={page.blocks} />;
  }

  // Plain WP page → render rendered content, then any [gravityform] embeds.
  return (
    <article className="py-12">
      <div className="container max-w-3xl">
        <h1 className="font-suse mb-6 text-3xl font-bold text-neutral-900 md:text-4xl">
          {page.title}
        </h1>
        <ParsedHtml
          as="div"
          className="prose-wp font-open-sans text-neutral-500"
          content={page.content}
        />

        {page?.formIds.map((formId) => (
          <div key={formId} className="mt-10">
            <GravityFormLoader formId={formId} />
          </div>
        ))}
      </div>
    </article>
  );
}
